title: Adrita Khan
logo: /assets/img/headshot_circle.png
description: Text below the image

theme: jekyll-theme-minimal

# Add your social media links here
linkedin: https://www.linkedin.com/in/adrita-khan
twitter: https://twitter.com/your-twitter
medium: https://medium.com/@your-medium
github: https://github.com/your-github
gitlab: https://gitlab.com/your-gitlab
